### ISSUE TITLE
Countdown timer

### ISSUE THREAD

**Issue by RW-17** [proginosko/LeechBlockNG-edge#1]
Hi, thanks for developing this amazing extension.
Currently I have an issue with the countdown timer that displays in one edge of the screen. The problem is that the size stays the same size (medium I think) even when selecting extra large. The position is correct but the size isn't. I don't mind it a lot but I would like to have it in the smaller size if possible.

Again, thanks a lot for the work your doing. I have attached a screenshot below (I did click save settings).

<img width="537" alt="LB_Bug" src="https://user-images.githubusercontent.com/75485731/132251323-88a3f884-9d5b-4967-9464-d82429616ea6.png">

**Comment by RW-17** [comment]
I've also tried the Chrome version (on Edge) and the same thing happens. Maybe is MS Edge's fault but I don't know.

**Comment by proginosko** [comment]
Thanks for the report! You're right. I had no idea, but this was broken in v1.0.12. It should be easy to fix though.
