### ISSUE TITLE
Rollover Time Issue w/ Moving Sets

### ISSUE THREAD

**Issue by dxmnkd316** [proginosko/LeechBlockNG-edge#2]
I like the new rollover option, but there's one issue.  If you set a rollover time and then move the set, the rollover doesn't follow.  It looks like it assumes the rollover from the set that previously held that position in the set list.  

Position 1 - Set A:  Rolled over 10 mins
Position 2 - Set B:  Rolled over 5 mins

*move set B to first position
Position 1 - Set B:  Shows rollover of 10 mins (should be 5)
Position 2 - Set A:  Shows rollover of 5 mins (should be 10)

Hopefully this clunky explanation makes sense.

**Comment by proginosko** [comment]
Thanks. This is a known issue, fixed in version 1.4.1, but not rolled out for Chrome and Edge yet. (Sorry! I hope to do that soon.)

**Comment by dxmnkd316** [comment]
No worries.  I didn't even think to check the list of resolved issues.  Thanks again for the hard work keeping us hard at work all these years.

**Comment by proginosko** [comment]
You're welcome!

I just uploaded version 1.4.2 for Edge, which fixes this issue.
