### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by plsfix1234** [proginosko/LeechBlockNG-edge#3]
The filter isn't working. Every time I try to save the option it goes blank. Can someone please fix it?

**Comment by proginosko** [comment]
Which filter? What "goes blank"?

**Comment by plsfix1234** [comment]
Let me elaborate. Whenever I pick the "Apply filter instead of blocking page" thing, like for example I pick grayscale, after i save it the option goes blank, and the filter doesn't apply when the options are met as well.

**Comment by proginosko** [comment]
So when you select "Apply filter" and save options, it appears unselected again? I'm just not sure what you mean by "the option goes blank."

Does that happen with any other options?

**Comment by plsfix1234** [comment]
No... I think it might be a glitch since it works now. Sorry for the inconvenience.

**Comment by proginosko** [comment]
Okay, no problem! I prefer glitches to bugs. 🙂
