### ISSUE TITLE
On Microsoft Edge, there is a way to circumvent blocking rules by using Read mode

### ISSUE THREAD

**Issue by michaeldacanay** [proginosko/LeechBlockNG-edge#6]
Example:

If I have a url, I can type `read:` + URL, and I can read the webpage even though the URL had the keyword or is a blocked website.

`read:https://thehill.com/homenews/senate/4348844-college-football-playoffs-senate/`

Desired behavior is to have the same behavior as if `read:` was not prepended.

**Comment by proginosko** [comment]
Thanks for the report. This should be fixed in the next release.
