### ISSUE TITLE
New release requires more permissions?

### ISSUE THREAD

**Issue by Cristy94** [proginosko/LeechBlockNG-edge#8]
My extension was blocked/disabled by Brave after the last update, saying that it requires more permissions than before.

What new permissions are required in 1.6.2?

I see for now it says:

```
Permissions
Read and change your browsing history on all your signed-in devices
Manage your downloads
```

What changed?

**Comment by proginosko** [comment]
The history permission. Version 1.6.2 added a requested feature: the option to add blocked pages to the browser history (so that they can be recovered later if desired).

**Comment by Cristy94** [comment]
> The history permission. Version 1.6.2 added a requested feature: the option to add blocked pages to the browser history (so that they can be recovered later if desired).

Ok, thanks. Just wanted to make sure you understand that adding more permissions automatically disables the extension and shows a warning for the user.

**Comment by proginosko** [comment]
Yes, I didn't know that, but I do now. 🙁
